### ISSUE TITLE
RoZ Release Checklist 

### ISSUE THREAD

**Issue by bran-van-d** [TabulaRasaXI/TabulaRasa#228]
## Leveling Up:
- [x] LB3 60-65 -- Confirmed by @ionian-exile 8/25
- [x] LB4 65-70 -- Confirmed by @ionian-exile 9/8
- [x] LB5 70-75 -- Confirmed by @ionian-exile 9/8
- [ ] Merits 
  - [x] Confirm players can collect merit points 
  - [x] Confirm players can spend merit points
  - [ ] Confirm players can sync and receive merit xp.

### Seiryu
 - [x] Steam Cleaner
 - [x] Mother Globe
 - [x] Can pop
 - [x] Drops items 
### Suzaku
 - [x] Brigandish Blade -- Confirmed by @ionian-exile 9/8
   - Curtana accessible
   - Buccanner Knife stealable
 - [x] Faust
   - Seems bugged -- he literally spammed Typhoon every 2-3 seconds. Would Cast it 2x, do one melee hit then spam it 2x more again, endlessly. Is this a TP skill? Otherwise it feels off
 - [x] Can pop 
 - [x] Drops items
### Byakko
 - [x] Despot
 - [x] Ullikummi
 - [x] Can pop
 - [x] Drops items 
### Genbu
 - [x] Zipacna -- Confirmed by @ionian-exile 9/8
 - [x] Olla Grande
   - Ro'maeve Water has 1% drop rate so I gave myself one heh -- all 3 NMs popped in succession as expected, and all hit like the magic pot trucks they are to a lv75
 - [x] Can pop
 - [x] Drops items
### Kirin
- [x] Can pop
- [x] Drops items 

## Dynamis 
-  [ ] Dynamis timer functional
-  [ ] Boss spawning
-  [ ] Consider entry fee
-  [ ] Nerf BLM Solo
## Zilart Missions
- [x] ZM1
- [x] ZM2
- [x] ZM3
- [x] ZM4
- [x] ZM5
- [x] ZM6
- [x] ZM7
- [x] ZM8
- [x] ZM9
- [x] ZM10
- [x] ZM11
- [x] ZM12
- [x] ZM13
- [x] Confirm Sky access after the above complete
- [x] ZM14
- [x] ZM15
- [x] ZM16
- [x] ZM17
- [x] ZM18

## In game fixes required from user reports
- [x] Take a look at magic accuracy
- [x] NM Persistence when server reboots

**Comment by austinclprojects** [comment]
>    - Seems bugged -- he literally spammed Typhoon every 2-3 seconds. Would Cast it 2x, do one melee hit then spam it 2x more again, endlessly. Is this a TP skill? Otherwise it feels off

That's just Faust stuff.

**Comment by bran-van-d** [comment]
Closing this as we have launched RoZ!
